Repository prysmaticlabs/ethereumapis, pull requests merged in 2020-04, with the labels that each got.

#118 Add subscribe method for committee ID subnet
  eth/v1alpha1/validator.pb.go
  eth/v1alpha1/validator.proto
Labels: ready for review

#121 Multiple Proposer Slots for Duties
  WORKSPACE
  eth/v1alpha1/beacon_chain.pb.go
  eth/v1alpha1/beacon_chain.proto
  eth/v1alpha1/validator.pb.go
  eth/v1alpha1/validator.proto
Labels: ready for review

#127 Add codeowners file
  .github/CODEOWNERS
Labels: ready for review

#113 Update proto definitions to spec v0.11
  WORKSPACE
  eth/v1alpha1/attestation.pb.go
  eth/v1alpha1/attestation.proto
  eth/v1alpha1/beacon_block.pb.go
  eth/v1alpha1/beacon_block.proto
  eth/v1alpha1/beacon_chain.pb.go
  eth/v1alpha1/beacon_chain.proto
  eth/v1alpha1/swagger_description.md
  eth/v1alpha1/validator.pb.go
  eth/v1alpha1/validator.proto
Labels: OK to merge

#129 Add back wait for chain start
  eth/v1alpha1/swagger_generated.pb.go
  eth/v1alpha1/validator.pb.go
  eth/v1alpha1/validator.proto
Labels: OK to merge, ready for review

#130 Add `StreamDuties`
  eth/v1alpha1/validator.pb.go
  eth/v1alpha1/validator.proto
Labels: OK to merge

#133 Include Go SSZ Tags By Default
  WORKSPACE
  eth/v1alpha1/BUILD.bazel
  eth/v1alpha1/attestation.proto
  eth/v1alpha1/beacon_block.proto
  eth/v1alpha1/beacon_chain.proto
  eth/v1alpha1/validator.proto
  tools/BUILD.bazel
  tools/ssz.bzl
Labels: ready for review

#136 Change all int64 to uint64
  eth/v1alpha1/generated.ssz.go
  eth/v1alpha1/validator.pb.go
  eth/v1alpha1/validator.proto
Labels: ready for review

#137 Add Validator Indices to Queue/Committee Instead of Public Keys
  eth/v1alpha1/beacon_chain.pb.go
  eth/v1alpha1/beacon_chain.proto
  eth/v1alpha1/generated.ssz.go
Labels: ready for review

#144 Turn StreamDuties into a Server-Side Stream
  eth/v1alpha1/generated.ssz.go
  eth/v1alpha1/validator.pb.go
  eth/v1alpha1/validator.proto
Labels: ready for review
