Repository prysmaticlabs/ethereumapis, pull requests merged in 2020-09, with the labels that each got.

#178 Add comments and params to BeaconState protos
  eth/v1/beacon_state.proto
Labels: ready for review

#179 Asserts that gfind is available on OSX, for protobufs updates
  scripts/common.sh
  scripts/update-go-pbs.sh
Labels: OK to merge, ready for review

#180 Add beacon blocks API protos
  eth/v1/beacon_blocks.proto
  eth/v1/beacon_state.proto
Labels: ready for review

#182 Regenerate Go Protos
  eth/v1alpha1/generated.ssz.go
  eth/v1alpha1/validator.pb.go
  eth/v1alpha1_gateway/validator.pb.go
  eth/v1alpha1_gateway/validator.pb.gw.go
Labels: OK to merge, ready for review

#183 Add weak subjectivity checkpoint
  eth/v1alpha1/beacon_chain.pb.go
  eth/v1alpha1/beacon_chain.proto
  eth/v1alpha1_gateway/beacon_chain.pb.go
  eth/v1alpha1_gateway/beacon_chain.pb.gw.go
Labels: ready for review

#186 Add debug protos for Eth2 APIs
  eth/v1/beacon_blocks.pb.go
  eth/v1/beacon_blocks.proto
  eth/v1/beacon_state.pb.go
  eth/v1/debug.proto
  eth/v1/generated.ssz.go
  eth/v1alpha1/generated.ssz.go
Labels: ready for review

#189 Refactor API services into 1 file/service
  eth/v1/BUILD.bazel
  eth/v1/beacon_blocks.pb.go
  eth/v1/beacon_blocks.proto
  eth/v1/beacon_chain_service.pb.go
  eth/v1/beacon_chain_service.proto
  eth/v1/beacon_debug.pb.go
  eth/v1/beacon_debug_service.pb.go
  eth/v1/beacon_debug_service.proto
  eth/v1/beacon_pool.pb.go
  eth/v1/beacon_pool.proto
  eth/v1/beacon_pools.pb.go
  eth/v1/beacon_state.pb.go
  eth/v1/beacon_state.proto
  eth/v1/beacon_states.pb.go
  eth/v1/beacon_states.proto
  eth/v1/config.pb.go
  eth/v1/config.proto
  eth/v1/generated.ssz.go
  eth/v1/validator.pb.go
  eth/v1/validator.proto
  eth/v1alpha1/generated.ssz.go
Labels: OK to merge

#190 Add Standard Eth2 API Node protos
  eth/v1/BUILD.bazel
  eth/v1/beacon_debug_service.pb.go
  eth/v1/node.pb.go
  eth/v1/node.proto
Labels: OK to merge

#191 Add Standard Eth2.0 API Validator protos
  eth/v1/BUILD.bazel
  eth/v1/beacon_chain_service.pb.go
  eth/v1/beacon_chain_service.proto
  eth/v1/generated.ssz.go
  eth/v1/validator_service.pb.go
  eth/v1/validator_service.proto
Labels: OK to merge, ready for review
