Repository prysmaticlabs/ethereumapis, pull requests merged in 2020-05, with the labels that each got.

#151 Update README
  README.md
Labels: ready for review

#153 Add More Generated SSZ Types
  eth/v1alpha1/BUILD.bazel
  eth/v1alpha1/generated.ssz.go
Labels: OK to merge

#157 Check in generated files for v1alpha gRPC gateway, add go mod support
  .bazelversion
  WORKSPACE
  eth/v1alpha1/BUILD.bazel
  eth/v1alpha1/attestation.pb.go
  eth/v1alpha1/beacon_block.pb.go
  eth/v1alpha1/beacon_chain.pb.go
  eth/v1alpha1/node.pb.go
  eth/v1alpha1/swagger_generated.pb.go
  eth/v1alpha1/validator.pb.go
  eth/v1alpha1_gateway/BUILD.bazel
  eth/v1alpha1_gateway/README.md
  eth/v1alpha1_gateway/attestation.pb.go
  eth/v1alpha1_gateway/beacon_block.pb.go
  eth/v1alpha1_gateway/beacon_chain.pb.go
  eth/v1alpha1_gateway/node.pb.go
  eth/v1alpha1_gateway/swagger_generated.pb.go
  eth/v1alpha1_gateway/validator.pb.go
  examples/integration/src/BUILD.bazel
  go.mod
  go.sum
  scripts/update-go-pbs.sh
  tools/ethereumapi_dependencies.bzl
Labels: ready for review

#159 Add gateway pb.gw.go files, update script
  eth/v1alpha1/generated.ssz.go
  eth/v1alpha1_gateway/attestation.pb.gw.go
  eth/v1alpha1_gateway/beacon_block.pb.gw.go
  eth/v1alpha1_gateway/beacon_chain.pb.gw.go
  eth/v1alpha1_gateway/node.pb.gw.go
  eth/v1alpha1_gateway/swagger_generated.pb.gw.go
  eth/v1alpha1_gateway/validator.pb.gw.go
  go.mod
  go.sum
  scripts/update-go-pbs.sh
Labels: OK to merge, ready for review
