Repository prysmaticlabs/ethereumapis, pull requests merged in 2020-02, with the labels that each got.

#88 Run Buildifer
  eth/v1alpha1/BUILD.bazel
Labels: OK to merge, ready for review

#98 Add StreamBlocks RPC endpoint
  eth/v1alpha1/beacon_chain.pb.go
  eth/v1alpha1/beacon_chain.proto
  eth/v1alpha1/validator.pb.go
Labels: OK to merge, ready for review

#101 Include Pagination Objects for Attestation Pool
  eth/v1alpha1/beacon_chain.pb.go
  eth/v1alpha1/beacon_chain.proto
Labels: enhancement

#105 Add balance details to `ValidatorPerformanceResponse`
  eth/v1alpha1/beacon_chain.pb.go
  eth/v1alpha1/beacon_chain.proto
Labels: enhancement

#106 Add Submit Attester/Proposer Slashing Endpoints
  eth/v1alpha1/beacon_chain.pb.go
  eth/v1alpha1/beacon_chain.proto
Labels: ready for review
